model_name: "llama-7b-se"
tokenizer_name: "hf-internal-testing/llama-tokenizer" 
reward_model_name: "llama-7b-se-rm"
log_with: "wandb"
save_freq: 100
batch_size: 8
gradient_accumulation_steps: 8
batched_gen: True
output_dir: results/
early_stopping: True
seed: 0
init_kl_coef: 0.2
